#!/usr/bin/env bash
#
# build-local-dmg.sh — build a Whisperly.dmg for personal / family use,
# without an Apple Developer Program membership.
#
# This produces an ad-hoc signed app (codesign identity "-"). The DMG is
# real and installable, but Gatekeeper will warn on first launch on each
# receiving Mac. See the "First-launch on the receiving Mac" instructions
# printed at the end of the build.
#
# No env vars required. No notarytool, no certs, no Apple ID.

set -euo pipefail

PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$PROJECT_ROOT"

PROJECT="whisperly.xcodeproj"
SCHEME="whisperly"
CONFIGURATION="Release"
BUILD_DIR="$PROJECT_ROOT/build"
ARCHIVE_PATH="$BUILD_DIR/whisperly-local.xcarchive"
EXPORT_DIR="$BUILD_DIR/export-local"
APP_PATH="$EXPORT_DIR/whisperly.app"
DMG_PATH="$BUILD_DIR/Whisperly-local.dmg"
DMG_STAGING="$BUILD_DIR/dmg-staging-local"

mkdir -p "$BUILD_DIR"
rm -rf "$ARCHIVE_PATH" "$EXPORT_DIR" "$DMG_STAGING" "$DMG_PATH"

# --- 0. (optional) inject bundled API keys ---
#
# If WHISPERLY_BUNDLED_GROQ_KEY and/or WHISPERLY_BUNDLED_ANTHROPIC_KEY are set
# in the environment, we overwrite whisperly/BundledKeys.swift in place so the
# archived .app contains the keys. The committed file (with `nil` defaults) is
# backed up first and restored on script exit (success OR failure) so a real
# key never reaches git.
#
# READ SIGNING.md → "Embedding API keys for family use" before turning this on.

KEYS_FILE="$PROJECT_ROOT/whisperly/BundledKeys.swift"
KEYS_BACKUP="$KEYS_FILE.bak"

restore_keys_file() {
  if [ -f "$KEYS_BACKUP" ]; then
    mv "$KEYS_BACKUP" "$KEYS_FILE"
    echo "▶︎ Restored BundledKeys.swift to nil defaults."
  fi
}
trap restore_keys_file EXIT

if [ -n "${WHISPERLY_BUNDLED_GROQ_KEY:-}" ] || [ -n "${WHISPERLY_BUNDLED_ANTHROPIC_KEY:-}" ]; then
  echo "▶︎ Injecting bundled API keys (will be restored to nil after build)..."
  cp "$KEYS_FILE" "$KEYS_BACKUP"
  # Format the optional Swift values: "key" if set, else nil.
  if [ -n "${WHISPERLY_BUNDLED_GROQ_KEY:-}" ]; then
    GROQ_LITERAL="\"${WHISPERLY_BUNDLED_GROQ_KEY}\""
  else
    GROQ_LITERAL="nil"
  fi
  if [ -n "${WHISPERLY_BUNDLED_ANTHROPIC_KEY:-}" ]; then
    ANTHROPIC_LITERAL="\"${WHISPERLY_BUNDLED_ANTHROPIC_KEY}\""
  else
    ANTHROPIC_LITERAL="nil"
  fi
  cat > "$KEYS_FILE" <<EOF
import Foundation

// AUTO-GENERATED by scripts/build-local-dmg.sh — do not commit.
// The committed version of this file declares nil defaults; that file is
// restored after the build completes. See SIGNING.md.
nonisolated enum BundledKeys {
    static let groqAPIKey: String? = ${GROQ_LITERAL}
    static let anthropicAPIKey: String? = ${ANTHROPIC_LITERAL}
    static var hasAnyBundled: Bool {
        (groqAPIKey?.isEmpty == false) || (anthropicAPIKey?.isEmpty == false)
    }
}
EOF
fi

# --- 1. archive (Release config, ad-hoc signed) ---

echo "▶︎ Archiving (ad-hoc signed)..."
xcodebuild \
  -project "$PROJECT" \
  -scheme "$SCHEME" \
  -configuration "$CONFIGURATION" \
  -destination "generic/platform=macOS" \
  -archivePath "$ARCHIVE_PATH" \
  CODE_SIGN_STYLE=Manual \
  CODE_SIGN_IDENTITY="-" \
  DEVELOPMENT_TEAM="" \
  CODE_SIGNING_REQUIRED=YES \
  CODE_SIGNING_ALLOWED=YES \
  archive

# --- 2. extract the .app from the archive ---
# We don't use `xcodebuild -exportArchive` here because that path requires
# an ExportOptions.plist with a `method` like "developer-id", which we're
# explicitly skipping. The .app inside the .xcarchive is already complete.

APP_IN_ARCHIVE="$ARCHIVE_PATH/Products/Applications/whisperly.app"
if [ ! -d "$APP_IN_ARCHIVE" ]; then
  echo "✗ Archive did not contain whisperly.app at the expected path." >&2
  exit 1
fi

mkdir -p "$EXPORT_DIR"
cp -R "$APP_IN_ARCHIVE" "$EXPORT_DIR/"

# --- 3. verify ad-hoc signature ---

echo "▶︎ Verifying signature..."
codesign --verify --verbose=2 "$APP_PATH" || true

# --- 3.5. smoke test: actually launch the .app ---
#
# `codesign --verify` only checks that the signature is internally consistent.
# It does NOT check that dyld can load the app at runtime, which is where
# subtler issues bite — e.g. Sparkle.framework being signed by a different
# team than the host app, with Hardened Runtime + Library Validation
# refusing to load it. We learned this the hard way once already.
#
# The test:
#   1. Copy the freshly-built .app to /tmp under a unique name (so we don't
#      collide with whatever the user has running in /Applications).
#   2. Strip quarantine just in case (defense in depth — local builds
#      shouldn't have it, but it's free insurance).
#   3. Snapshot the count of whisperly crash reports before launching.
#   4. `open` the app, give it 5s.
#   5. If the process isn't running OR a new crash report appeared, fail
#      the build and print the crash reason. Otherwise kill the test
#      process cleanly and proceed.
#
# Set SKIP_SMOKE_TEST=1 to bypass (e.g. in CI without a windowserver).

if [ "${SKIP_SMOKE_TEST:-0}" = "1" ]; then
  echo "▶︎ Smoke test: skipped (SKIP_SMOKE_TEST=1)"
else
  echo "▶︎ Smoke test: launching the .app to verify it actually loads..."
  SMOKE_DIR="/tmp/whisperly-smoketest-$$"
  SMOKE_APP="$SMOKE_DIR/Whisperly.app"
  CRASH_DIR="$HOME/Library/Logs/DiagnosticReports"

  cleanup_smoketest() {
    # Best-effort kill of anything we launched, then remove the temp copy.
    local pids
    pids=$(pgrep -f "$SMOKE_APP/Contents/MacOS" 2>/dev/null || true)
    if [ -n "$pids" ]; then
      # shellcheck disable=SC2086
      kill $pids 2>/dev/null || true
      sleep 1
      # shellcheck disable=SC2086
      kill -9 $pids 2>/dev/null || true
    fi
    rm -rf "$SMOKE_DIR"
  }
  # Compose with the existing trap (which restores BundledKeys.swift).
  trap 'cleanup_smoketest; restore_keys_file' EXIT

  mkdir -p "$SMOKE_DIR"
  cp -R "$APP_PATH" "$SMOKE_APP"
  xattr -cr "$SMOKE_APP" 2>/dev/null || true

  CRASH_BEFORE=$(ls "$CRASH_DIR"/whisperly-*.ips 2>/dev/null | wc -l | tr -d ' ')
  open "$SMOKE_APP"
  sleep 5
  CRASH_AFTER=$(ls "$CRASH_DIR"/whisperly-*.ips 2>/dev/null | wc -l | tr -d ' ')
  ALIVE_PID=$(pgrep -f "$SMOKE_APP/Contents/MacOS" | head -1 || true)

  if [ "$CRASH_AFTER" -gt "$CRASH_BEFORE" ]; then
    LATEST_CRASH=$(ls -t "$CRASH_DIR"/whisperly-*.ips 2>/dev/null | head -1)
    echo "✗ Smoke test FAILED — app crashed during launch."
    echo ""
    if [ -n "$LATEST_CRASH" ]; then
      echo "  Latest crash report: $LATEST_CRASH"
      echo "  Termination reason:"
      # The .ips file is two JSON objects; grep the structured 'reasons' field
      # from the second one and print just enough to identify the cause.
      python3 -c "
import json, sys
with open('$LATEST_CRASH') as f:
    f.readline()  # skip header line
    obj = json.load(f)
term = obj.get('termination', {})
ind = term.get('indicator', '')
reasons = term.get('reasons', [])
print(f'    indicator: {ind}')
for r in reasons[:3]:
    print(f'    - {r[:300]}')
" 2>/dev/null || tail -5 "$LATEST_CRASH"
    fi
    echo ""
    echo "  Common causes:"
    echo "    - Missing entitlement (com.apple.security.cs.disable-library-validation"
    echo "      is required for Sparkle 2 + Hardened Runtime + ad-hoc on macOS 14+)"
    echo "    - Embedded framework signed by a different team than the host"
    echo "    - Missing dylib at @rpath"
    echo ""
    echo "  Re-run with SKIP_SMOKE_TEST=1 to build a DMG anyway (e.g. for"
    echo "  manual debugging), but DO NOT distribute that DMG."
    exit 1
  fi

  if [ -z "$ALIVE_PID" ]; then
    echo "✗ Smoke test FAILED — app exited within 5s without leaving a crash report."
    echo "  This usually means Hardened Runtime killed it silently. To debug:"
    echo "    log stream --process whisperly --level debug &"
    echo "    open '$APP_PATH'"
    exit 1
  fi

  echo "✓ Smoke test passed (PID $ALIVE_PID alive after 5s, no new crash report)."
fi

# --- 4. build the DMG ---

echo "▶︎ Building DMG..."
mkdir -p "$DMG_STAGING"
# Capitalize the bundle name as it appears in the DMG (the build target is
# 'whisperly' lowercase; users expect 'Whisperly.app').
cp -R "$APP_PATH" "$DMG_STAGING/Whisperly.app"
ln -s /Applications "$DMG_STAGING/Applications"

hdiutil create \
  -volname "Whisperly" \
  -srcfolder "$DMG_STAGING" \
  -ov \
  -format UDZO \
  -fs HFS+ \
  "$DMG_PATH"

# --- done ---

cat <<EOF

✓ $DMG_PATH

────────────────────────────────────────────────────────────────────
First-launch instructions for the receiving Mac
────────────────────────────────────────────────────────────────────

Because this app isn't signed with an Apple Developer ID, macOS Gatekeeper
will refuse to open it the first time. Pick whichever of the two options
feels easier — both are completely safe for an app you built yourself.

Option A — System Settings (one click, no Terminal):
  1. Mount the DMG and drag Whisperly.app to /Applications.
  2. Try to open Whisperly. macOS will show "Whisperly cannot be opened
     because Apple cannot check it for malicious software."
  3. Click "Done" / "Cancel" on that dialog.
  4. Open System Settings → Privacy & Security.
  5. Scroll down — there's a line: "Whisperly was blocked from use
     because it is not from an identified developer."
  6. Click "Open Anyway" next to it. Confirm with your password / Touch ID.
  7. Whisperly opens. macOS remembers the decision; next launches are fine.

Option B — Terminal (one command, instant):
  After dragging Whisperly.app to /Applications, open Terminal and run:

      xattr -cr /Applications/Whisperly.app

  That strips the macOS "downloaded from the internet" quarantine flag.
  Then double-click Whisperly normally.

────────────────────────────────────────────────────────────────────
EOF

ls -lh "$DMG_PATH"
